baseURL = "https://beyondeye.github.io/aitasks/"
title = "aitasks"
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableGitInfo = true

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.155.3"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

[params]
  github_repo = "https://github.com/beyondeye/aitasks"
  github_project_repo = "https://github.com/beyondeye/aitasks"
  github_subdir = "website"
  offlineSearch = true

[params.ui]
  sidebar_menu_compact = true
  breadcrumb_disable = false
  navbar_logo = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "tango"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
